services:
  catalogdb:
    image: postgres:18

  basketdb:
    image: postgres:18

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/CatalogAPI/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
