services:
  catalogdb:
    image: postgres:18

  basketdb:
    image: postgres:18

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/CatalogAPI/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: services/basket/BasketAPI/Dockerfile

  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: services/discount/DiscountGrpc/Dockerfile

  orderingapi:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: services/ordering/OrderingAPI/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile
  
  shoppingweb:
    image: ${DOCKER_REGISTRY-}shoppingweb
    build:
      context: ./WebApps/shopping-web-react
      dockerfile: Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  sqlserver_orderdb:




